// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/api/trust.ts";
import * as $$0 from "./islands/TrustCalculator.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/api/trust.ts": $1,
  },
  islands: {
    "./islands/TrustCalculator.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
